semgrep:
  image: returntocorp/semgrep
  script: semgrep ci
  rules:
  - changes:
      - .gitlab-ci.yml
  - if: $CI_PIPELINE_SOURCE == "web"  # allow triggering a scan manually from the gitlab UI
  - if: $CI_MERGE_REQUEST_IID
  
  variables:
    
    SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN
  
  # Setup inline MR comments:
  # https://semgrep.dev/docs/semgrep-app/notifications/#enabling-gitlab-merge-request-comments
